export const VILLAIN_SET_LOCATION = 'VILLAIN_SET_LOCATION';
export const VILLAIN_SET_POSSIBLE_LOCATION_ATTACKS = 'VILLAIN_SET_POSSIBLE_LOCATION_ATTACKS';
export const VILLAIN_FETCHING = 'VILLAIN_FETCHING';

export const VILLAIN_SET_POSSIBLE_LOCATION = 'VILLAIN_SET_POSSIBLE_LOCATION';
