export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTHENTICATION_FAIL = 'AUTHENTICATION_FAIL';
export const AUTHENTICATION_COMPLETE = 'AUTHENTICATION_COMPLETE';


export const GET_PLACE = 'GET_PLACE';
export const GET_PLACE_FAIL = 'GET_PLACE_FAIL';
export const GET_PLACE_SUCCESS = 'GET_PLACE_SUCCESS';
export const GET_PLACE_REVIEWS_SUCCESS = 'GET_PLACE_REVIEWS_SUCCESS';

export const GET_PLACE_PHOTOS_SUCCESS = 'GET_PLACE_PHOTOS_SUCCESS';
